/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package fi.jamk.Elokuvarekisteri;

import java.awt.Image;
import java.io.IOException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author F7347
 */
public class MuokkaaElokuvaJDialog extends javax.swing.JDialog {
    private Elokuvamalli elokuvamalli = new Elokuvamalli();
    private int muokattavaId;
    private Image image;
    /**
     * Creates new form LisaaElokuvaJDialog
     */
    public MuokkaaElokuvaJDialog(ElokuvarekisteriUI parent, boolean modal, int id) {
        super(parent, modal);
        muokattavaId = id;
        initComponents();
        
        Elokuva elokuva = this.elokuvamalli.getElokuvaAt(id);
        
        nimiTxtField.setText(elokuva.getNimi());
        ohjaajaTxtField.setText(elokuva.getOhjaaja());
        nayttelijatTxtField.setText(elokuva.getNayttelijat());
        lajiTxtField.setText(elokuva.getLajityyppi());
        julkaisuvuosiTxtField.setText(elokuva.getJulkaisuvuosi());
        pituusTxtField.setText(elokuva.getPituus());
        juoniTxtField.setText(elokuva.getJuoni());
        
        try {
            URL url = new URL(elokuva.getKuvaUrl());
            image = null;
            image = ImageIO.read(url);
            System.err.println("kuva ladattu");
        } catch (IOException ex) {
            Logger.getLogger(ElokuvarekisteriUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("Kaytan kuvaa");

                    // määritellään uusi imageIcon joka on image(luettu url)
                    ImageIcon kuva1 = new ImageIcon(image);
                    // muutetaan imageIcon kuvaksi jonka nimi on elokuvankuva
                    Image elokuvankuva = kuva1.getImage();
                    // skaalataan elokuvan kuva pienemmäksi
                    Image pienennettykuva = elokuvankuva.getScaledInstance(140, 200, java.awt.Image.SCALE_SMOOTH);
                    // laitetaan kuva1 paikalle pienennetty kuva
                    kuva1 = new ImageIcon(pienennettykuva);
                    // asettetaan kuva labeliin imageicon kuva1
                    kuvafield.setIcon(kuva1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nimiTxtField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        julkaisuvuosiTxtField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lajiTxtField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ohjaajaTxtField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        nayttelijatTxtField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        pituusTxtField = new javax.swing.JTextField();
        valmisBtn = new javax.swing.JButton();
        peruutaBtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        juoniTxtField = new javax.swing.JTextField();
        kuvafield = new javax.swing.JLabel();

        jLabel4.setText("jLabel2");

        jTextField3.setText("jTextField1");

        jLabel6.setText("jLabel2");

        jTextField5.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Muokkaa Elokuvaa");

        jLabel2.setText("Nimi:");

        jLabel3.setText("Julkaisuvuosi:");

        jLabel5.setText("Lajityyppi:");

        jLabel7.setText("Ohjaaja:");

        jLabel8.setText("Näyttelijät:");

        jLabel9.setText("Pituus:");

        valmisBtn.setText("Valmis");
        valmisBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valmisBtnActionPerformed(evt);
            }
        });

        peruutaBtn.setText("Peruuta");
        peruutaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peruutaBtnActionPerformed(evt);
            }
        });

        jLabel10.setText("Juoni:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(valmisBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(peruutaBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(juoniTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(julkaisuvuosiTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lajiTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nayttelijatTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ohjaajaTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pituusTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nimiTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(kuvafield, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nimiTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(julkaisuvuosiTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lajiTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ohjaajaTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(nayttelijatTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(pituusTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(kuvafield, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(juoniTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valmisBtn)
                    .addComponent(peruutaBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void valmisBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valmisBtnActionPerformed
        // TODO add your handling code here:
      /* 
        Elokuva e = new Elokuva(elokuvamalli.getLastId()+1,
                nimiTxtField.getText(), 
                ohjaajaTxtField.getText(), 
                nayttelijatTxtField.getText(), 
                lajiTxtField.getText(), 
                julkaisuvuosiTxtField.getText(), 
                pituusTxtField.getText(), 
                juoniTxtField.getText(),
                "");
        
        elokuvamalli.lisaa(e);
        */
       /* 
        Henkilo henkilo = this.henkilomalli.getHenkiloAt(muokattavaId);
        henkilomalli.setValueAt(EtunimiTextField.getText(), henkilo.getId(), 1);
        henkilomalli.setValueAt(SukunimiTextField.getText(), henkilo.getId(), 2);
        henkilomalli.setValueAt(Integer.parseInt(SyntymavuosiTextField.getText()), henkilo.getId(), 3);
        henkilomalli.setValueAt(KotimaaTextField.getText(), henkilo.getId(), 4);
        henkilomalli.setValueAt(RooliComboBox.getSelectedItem().toString(), henkilo.getId(), 5);  
        */
        
        Elokuva elokuva = this.elokuvamalli.getElokuvaAt(muokattavaId);
        
        elokuvamalli.setValueAt(nimiTxtField.getText(),elokuva.getId(), 1);
        elokuvamalli.setValueAt(ohjaajaTxtField.getText(),elokuva.getId(), 2);
        elokuvamalli.setValueAt(nayttelijatTxtField.getText(),elokuva.getId(), 3);
        elokuvamalli.setValueAt(lajiTxtField.getText(),elokuva.getId(), 4);
        elokuvamalli.setValueAt(julkaisuvuosiTxtField.getText(),elokuva.getId(), 5);
        elokuvamalli.setValueAt(pituusTxtField.getText(),elokuva.getId(), 6);
        elokuvamalli.setValueAt(juoniTxtField.getText(),elokuva.getId(), 7);
        dispose();
        
    }//GEN-LAST:event_valmisBtnActionPerformed

    private void peruutaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peruutaBtnActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_peruutaBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField julkaisuvuosiTxtField;
    private javax.swing.JTextField juoniTxtField;
    private javax.swing.JLabel kuvafield;
    private javax.swing.JTextField lajiTxtField;
    private javax.swing.JTextField nayttelijatTxtField;
    private javax.swing.JTextField nimiTxtField;
    private javax.swing.JTextField ohjaajaTxtField;
    private javax.swing.JButton peruutaBtn;
    private javax.swing.JTextField pituusTxtField;
    private javax.swing.JButton valmisBtn;
    // End of variables declaration//GEN-END:variables
}
